USE [master]
GO

/****** Object:  Database [LibraryDrill]    Script Date: 1/25/2017 2:03:24 AM ******/
CREATE DATABASE [LibraryDrill]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LibraryDrill', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\LibraryDrill.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LibraryDrill_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\LibraryDrill_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LibraryDrill] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LibraryDrill].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LibraryDrill] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LibraryDrill] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LibraryDrill] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LibraryDrill] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LibraryDrill] SET ARITHABORT OFF 
GO

ALTER DATABASE [LibraryDrill] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LibraryDrill] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [LibraryDrill] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LibraryDrill] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LibraryDrill] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LibraryDrill] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LibraryDrill] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LibraryDrill] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LibraryDrill] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LibraryDrill] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LibraryDrill] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LibraryDrill] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LibraryDrill] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LibraryDrill] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LibraryDrill] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LibraryDrill] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LibraryDrill] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LibraryDrill] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LibraryDrill] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LibraryDrill] SET  MULTI_USER 
GO

ALTER DATABASE [LibraryDrill] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LibraryDrill] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LibraryDrill] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LibraryDrill] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LibraryDrill] SET  READ_WRITE 
GO

